### ISSUE TITLE
Can a customised file be cleaned with the help of this?

### ISSUE THREAD

**Issue by MBhuvana1991** [fraimondo/eeg_cleaner#1]
Can a customised file be cleaned with the help of this? Where and how to run the files in script folder?? Kindly explain the detail installation and usage procedure

**Comment by fraimondo** [comment]
Hi. You can clean any EEG file as long as you know how to read it. The idea of this tool is to provide helper scripts, not to be a point and click tool. You need to have some knowledge about Python and in particular MNE-Python. 

In the README file you have instructions on how to install and in the examples folder how to use it. However, if you are not familiar with Python nor MNE-Python, this tool will not help you much.

**Comment by MBhuvana1991** [comment]
Hi
   Can you tell me where the output/cleaned file will be stored??? or is
it  possible to restore the cleaned file separately?
regards,

*M.Bhuvaneshwari,*
*Research Scholar,*
*Karunya Institute of technology and Sciences*

*Coimbatore.*

**Comment by fraimondo** [comment]
This set of tools work in combination with custom scripts that you need to create. It is up to you to save the files.

**Comment by MBhuvana1991** [comment]
Ok thank you for the quick response.
